### ISSUE TITLE
How to prevent ban?

### ISSUE THREAD

**Issue by Quattuorlift** [zhangjk95/MahjongAI#9]

**Comment by zhangjk95** [comment]
I added a random delay mechanism in the latest version. https://github.com/zhangjk95/MahjongAI/commit/48d94e06c6d084638bda2ce05f99e57bbdbeb3dc But still, this will not completely solve the problem. The best way to prevent a ban is not to run this AI for too long. Please understand that the game is supposed to be played by humans and you are using this AI at your own risk.

**Comment by Quattuorlift** [comment]
My account got banned after running this AI for 48 hours constantly.It was really careless of me XD.And simply out of curiosity,is there anyway to detect AI just by analysing data transmission?

**Comment by zhangjk95** [comment]
I'm sorry to hear that.

Regarding the difference in data transmitted, I think there is a lot, such as whether a player fetches game resources (image/audio files / css / js / ...), whether a player fetches more information (daily quests / announcements / ...), the time spent loading the game, the time spent taking each move, etc.

However, for now there is no automatic detection in the game, so my guess is that you probably got reported by another player. The AI sometimes operates too fast, and that's why you got reported. I think adding a random delay to each move can address the problem to some extent.

**Comment by Quattuorlift** [comment]
Thanks for your reply.
